### PR TITLE
React to connectivity changes when playing videos

### PR DESCRIPTION
**Pull request by joshmcarthur**
Added [Reachability](https://github.com/ashleymills/Reachability.swift), which seems to be the accepted method in iOS for querying the connection state of the device.

Also add UI to display when the device is offline.

Demo:

Demo

Note that the simulator picks up network changes correctly, but the iPad I am testing on does not. It also does not affect the application from functioning, and I don't have an iPhone to test with. I'd like to release this and fix it if necessary (it's possible that the iPad is just not picking up the changes correctly)

### CODE REVIEW

**Comment by joshmcarthur** [comment]
Just a thought, but the issue with connectivity changes not working on the iPad could possibly be an iOS 10 issue?

**Comment by eoinkelly** [comment]
Do you definitely need to involve the reachability API given that the only thing that needs network access is the video - would it be possible to catch errors from the video view and show the UI instead?

**Comment by joshmcarthur** [comment]
@eoinkelly that exists at the moment, that error handling. The problem I ran into is that while error handling is built into the video player (there is a state change notification that can be subscribed to), the timeout for the video cannot be configured, and an error is not thrown until the video player times out (from memory this is 30 seconds or 1 minute). When I was researching solutions, there were a few that suggested subscribing to load state notifications on the player, and reacting if, for example the load state had not changed for 10 seconds, and honestly I didn't really try this route, but it is closest to what you are suggesting.

The reason I went with Reachability was that it was pretty widely suggested all over the place, so I thought if I had problems with it it would be easier to find StackOverflow answers. I also thought it would be better UX to show a view to the user stating that the video will not work because they are offline, before they try and play it.

**Comment by eoinkelly** [comment]
Sweet - that sounds good. You will still need to update the min iOS version to 8.0 tho as Reachability.swift only supports that. Updating to iOS 8.0 isn't a big deal I think as it only cuts off iPhone 4 and iPad 1

**Comment by joshmcarthur** [comment]
@eoinkelly I have made some fairly significant changes:

1. I have switched the Swift version for the Objective C version. That was a nice spot you made about the Swift version supporting iOS 8, and I was having trouble with the Swift version not working on iOS 10 in any case. The Objective C version works on iOS 10 and is also backwards compatible as far back as our current minimum, iOS 7. I'm keen to support as old as possible as educational institutes, etc may use this app on older hardware.
2. I discovered that the iPad layout basically has the same code as the video view controller copy and pasted. I'd like to clean this up, but don't have the iOS skills to know how to do this right now (I suspect a custom view class is involved...?), so I have added similar behaviour as the iPhone layout. The only difference is that I just could not get a custom view to position correctly on the iPad - something to do with the frame of the split view controller I think. Instead, I disable the play button and change the text to reflect the error.

**Comment by eoinkelly** [comment]
XCode 8 only supports back as far as iOS 8 so I think that change will have to happen. I'm sympathetic to keeping this working on older devices _but_  the iPad 2 and iPhone 4S went on sale in 2011 so any device purchased in the last 6 years should be fine and that seems like a reasonable cutoff.

Also the app store will continue to make the older versions of the app available to older devices so they won't be entirely cut off.

**Pull request merged**
